### ISSUE TITLE
The request matched multiple endpoints.

### ISSUE THREAD

**Issue by danijeljw-RPC** [repasscloud/optechx.api#2]
```csharp
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

webapp6.Controllers.ApplicationController.GetApplication (webapp6)
webapp6.Controllers.ApplicationController.GetApplication (webapp6)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by danijeljw-RPC** [comment]
Swap the `UID` from using `/` or `_` to `::`

**Comment by danijeljw-RPC** [comment]
Resolved by testing with commit https://github.com/repasscloud/optechx.api/commit/bf2fe59ffd288cafff92148b07cca5f343ac2ac5
